### ISSUE TITLE
TypeError: 'Unique Visitor' is not JSON serializable

### ISSUE THREAD

**Issue by doganmeh** [django-request/django-request#168]
I just installed django-request, and got this error:

```
Internal Server Error: /admin/request/request/overview/traffic/
Traceback (most recent call last):
  File "/home/venvs/edgle/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/venvs/edgle/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/venvs/edgle/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/prog/django-request/request/admin.py", line 56, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/venvs/edgle/lib/python3.5/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/venvs/edgle/lib/python3.5/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/venvs/edgle/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/home/prog/django-request/request/admin.py", line 94, in traffic
    return HttpResponse(json.dumps(modules.graph(days_qs)), content_type='text/javascript')
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 'Unique Visitor' is not JSON serializable
```

graph label seemed to be a string but it actually was not; casting it in traffic.Modules.graph fixed it for me. If wanted, I can create a pull request.

**Comment by felixxm** [comment]
Thanks for the report. Feel-free to prepare a patch :+1:
