### ISSUE TITLE
Invalid UTF-8 in User-Agent header triggers a Python traceback

### ISSUE THREAD

**Issue by trou** [django-request/django-request#187]
Hello,
a crawler with a weird user-agent triggered the following trace in our site (reproducible with django-request v1.5.4):
```
2019-01-22 05:33:30,318 ERROR: django.request Internal Server Error: /
Traceback (most recent call last):
  File "/srv/vhosts/www/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/srv/vhosts/www/env/local/lib/python2.7/site-packages/request/middleware.py", line 41, in process_response
    r.from_http_request(request, response)
  File "/srv/vhosts/www/env/local/lib/python2.7/site-packages/request/models.py", line 85, in from_http_request
    self.save()
  File "/srv/vhosts/www/env/local/lib/python2.7/site-packages/request/models.py", line 123, in save
    super(Request, self).save(*args, **kwargs)
  File "/srv/vhosts/www/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/srv/vhosts/www/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/srv/vhosts/www/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/srv/vhosts/www/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/srv/vhosts/www/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/vhosts/www/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/srv/vhosts/www/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/srv/vhosts/www/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/vhosts/www/env/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/vhosts/www/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
DataError: invalid byte sequence for encoding "UTF8": 0xa3
```
It is easy to reproduce with curl: `curl --user-agent $(echo -en "\xa3\xa9") http://example.com`

**Comment by felixxm** [comment]
Python 2.7 is not supported anymore and I cannot reproduce it on the current `master` branch.
