### ISSUE TITLE
test_day and test_day_without_date failures

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [django-request/django-request#241]
While debugging a build failure for openSUSE, I discovered test_day and test_day_without_date failed in tests/test_managers.py due to the timezone falling through to America/Chicago and therefore not matching any records.

Overriding the settings as in other tests in that file fixed the failure:

```
--- django-request.orig/tests/test_managers.py
+++ django-request/tests/test_managers.py
@@ -134,12 +134,14 @@ class RequestQuerySetTest(TestCase):
         qs = Request.objects.all().week(year='foo', week='1')
         self.assertIsNone(qs)
 
+    @override_settings(USE_TZ=True, TIME_ZONE='Africa/Nairobi')
     def test_day(self):
         qs = Request.objects.all().day(date=now())
         self.assertEqual(1, qs.count())
         qs = Request.objects.all().day(date=now() - timedelta(days=3))
         self.assertEqual(0, qs.count())
 
+    @override_settings(USE_TZ=True, TIME_ZONE='Africa/Nairobi')
     def test_day_without_date(self):
         qs = Request.objects.all().day(
             year=str(now().year),
```

**Comment by felixxm** [comment]
@s-t-e-v-e-n-k Thanks for this report :+1: however, I cannot reproduce tests failures with `America/Chicago`.

**Comment by s-t-e-v-e-n-k** [comment]
America/Chicago was what the system was returning as a fallback timezone. I can show you a pdb traceback if that would help.

**Comment by felixxm** [comment]
> America/Chicago was what the system was returning as a fallback timezone.

Yes, and it's used also by GitHub actions without any [issues](https://github.com/django-request/django-request/actions?query=branch%3Amaster+event%3Apush) :thinking: .

> I can show you a pdb traceback if that would help.

Please do.

**Comment by jayvdb** [comment]
This is the output from the openSUSE build workers, only happens occasionally of course.

```py
[   32s] ======================================================================
[   32s] FAIL: test_day (tests.test_managers.RequestQuerySetTest)
[   32s] ----------------------------------------------------------------------
[   32s] Traceback (most recent call last):
[   32s]   File "/usr/lib/python3.9/site-packages/django/test/utils.py", line 460, in inner
[   32s]     return func(*args, **kwargs)
[   32s]   File "/home/abuild/rpmbuild/BUILD/django-request-1.6.1/tests/test_managers.py", line 140, in test_day
[   32s]     self.assertEqual(1, qs.count())
[   32s] AssertionError: 1 != 0
[   32s] 
[   32s] ======================================================================
[   32s] FAIL: test_day_without_date (tests.test_managers.RequestQuerySetTest)
[   32s] ----------------------------------------------------------------------
[   32s] Traceback (most recent call last):
[   32s]   File "/usr/lib/python3.9/site-packages/django/test/utils.py", line 460, in inner
[   32s]     return func(*args, **kwargs)
[   32s]   File "/home/abuild/rpmbuild/BUILD/django-request-1.6.1/tests/test_managers.py", line 151, in test_day_without_date
[   32s]     self.assertEqual(1, qs.count())
[   32s] AssertionError: 1 != 0
```
